<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Interview;

class InterviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $interviews = [
            ['id' => 1, 'service_cat_id' => 1, 'title' => ' Grundutredning + Säkerhetsprövningsintervju - Video', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 2, 'service_cat_id' => 1, 'title' => ' Grundutredning + Säkerhetsprövningsintervju - Fysiskt', 'desc' => '', 'place' => 1, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 3, 'service_cat_id' => 1, 'title' => 'SPI - klass 2 - Video', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 4, 'service_cat_id' => 1, 'title' => 'SPI - klass 2 - Fysikt', 'desc' => '', 'place' => 1, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 10, 'service_cat_id' => 3, 'title' => 'Background check - Level  1 ', 'desc' => '● Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 2],
            ['id' => 12, 'service_cat_id' => 3, 'title' => 'Background check - Level 2', 'desc' => '● Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De tre (3) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n● CV­ kontroll\r\n● Sociala medier', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 5],
            ['id' => 13, 'service_cat_id' => 3, 'title' => 'Background check - Level  3', 'desc' => '<p>Personalia<br />Finance<br />Legal history<br />CV check<br />Internet exposure<br />Social Media<br />Property ownership<br />Company involvement</p>', 'place' => 0, 'country' => 1, 'cost' => 0, 'delivery_days' => null],
            ['id' => 17, 'service_cat_id' => 3, 'title' => 'Sefina - Nivå 1', 'desc' => '● Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 18, 'service_cat_id' => 3, 'title' => 'Background check - Screening ', 'desc' => ' test', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 19, 'service_cat_id' => 3, 'title' => 'Dekra - Bakgrundskontroll nivå 1', 'desc' => 'Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 20, 'service_cat_id' => 3, 'title' => 'ISS - Bakgrundskontroll nivå 1', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 2],
            ['id' => 21, 'service_cat_id' => 3, 'title' => 'Sefina - Nivå 2', 'desc' => '● Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n● CV­ kontroll\r\n● Sociala medier', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 22, 'service_cat_id' => 3, 'title' => 'Sefina - Nivå 3', 'desc' => '● Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n● CV­ kontroll\r\n● Sociala medier\r\n● Internetexponering\r\n● Kontroll av make/makas bolagsengagemang\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 23, 'service_cat_id' => 3, 'title' => 'Sefina - Personutredning', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 25, 'service_cat_id' => 1, 'title' => 'Scania - SPI - Video', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 26, 'service_cat_id' => 1, 'title' => 'Scania - SPI - Fysiskt', 'desc' => '', 'place' => 1, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 27, 'service_cat_id' => 3, 'title' => 'Scania - Nivå 1', 'desc' => 'Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 28, 'service_cat_id' => 3, 'title' => 'Scania - Nivå 2', 'desc' => 'Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 29, 'service_cat_id' => 3, 'title' => 'Scania - Nivå 3', 'desc' => 'Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 30, 'service_cat_id' => 3, 'title' => 'Northvolt Level 1', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 31, 'service_cat_id' => 3, 'title' => 'Northvolt Level 2', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 33, 'service_cat_id' => 7, 'title' => 'Personutredning', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => null, 'delivery_days' => null],
            ['id' => 35, 'service_cat_id' => 1, 'title' => 'SK - SPI - Fysiskt klass 3', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 36, 'service_cat_id' => 1, 'title' => 'SK - SPI - Fysiskt klass 2', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 37, 'service_cat_id' => 1, 'title' => 'SK - SPI - Digital klass 3', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 38, 'service_cat_id' => 1, 'title' => 'SK - SPI - Digital klass 2', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 42, 'service_cat_id' => 9, 'title' => 'Uppföljningssamtal ', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 43, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll nivå 1 - Nuvia', 'desc' => '● Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 2],
            ['id' => 44, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll nivå 2 - Nuvia', 'desc' => '● Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (2) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n● CV­ kontroll\r\n● Sociala medier', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 8],
            ['id' => 45, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll BAS - Landskrona Kommun ', 'desc' => '● Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (3) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 46, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll Utökad - Landskrona Kommun ', 'desc' => '● Verifiering av personnummer.\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.\r\n● De två (3) sista deklarerade årsinkomsterna.\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n● CV­ kontroll\r\n● Sociala medier', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 47, 'service_cat_id' => 9, 'title' => 'Uppföljningssamtal - Landskrona stad', 'desc' => 'Årliga uppföljningssamtal enligt säkerhetsskyddslagen i Sverige är en del av arbetet med att säkerställa att anställda och andra personer med tillgång till säkerhetsklassad information eller verksamhet fortfarande är pålitliga ur säkerhetssynpunkt. Dessa samtal syftar till att uppdatera säkerhetsbedömningar och säkerställa att tidigare bedömningar om personens pålitlighet, lojalitet och sårbarhet är aktuella. De hjälper också till att identifiera eventuella förändringar i personens livssituation som kan påverka deras säkerhetsbedömning, såsom ekonomiska problem, nya relationer eller förändrade arbetsförhållanden. Dessutom bidrar samtalen till att stärka individens medvetenhet om säkerhetsskyddsfrågor och deras eget ansvar för att skydda känslig information. Genom dessa samtal kan organisationer vidta åtgärder för att hantera eventuella identifierade säkerhetsrisker och upprätthålla en hög säkerhetsnivå.', 'place' => 1, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 48, 'service_cat_id' => 1, 'title' => ' Grundutredning + Säkerhetsprövningsintervju - Fysiskt - Landskrona stad', 'desc' => '<p>När kunden lägger sin beställning, anger de nödvändiga uppgifter såsom namn och kontaktinformation för kandidaten. Recway skickar därefter en bekräftelse på mottagandet av beställningen och informerar om nästa steg i processen. Kandidaten får ett informationsmejl från Recway med detaljer om intervjun, vad som förväntas och vilka dokument de ska ta med sig. Beställaren får en statusuppdatering som innehåller detaljer om intervjutiden och platsen.</p>', 'place' => 1, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 49, 'service_cat_id' => 1, 'title' => ' Grundutredning + Säkerhetsprövningsintervju - Video - Landskrona stad', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 50, 'service_cat_id' => 9, 'title' => 'Uppföljningssamtal - Sundsvall Kommun', 'desc' => 'Årliga uppföljningssamtal enligt säkerhetsskyddslagen i Sverige är en del av arbetet med att säkerställa att anställda och andra personer med tillgång till säkerhetsklassad information eller verksamhet fortfarande är pålitliga ur säkerhetssynpunkt. Dessa samtal syftar till att uppdatera säkerhetsbedömningar och säkerställa att tidigare bedömningar om personens pålitlighet, lojalitet och sårbarhet är aktuella. De hjälper också till att identifiera eventuella förändringar i personens livssituation som kan påverka deras säkerhetsbedömning, såsom ekonomiska problem, nya relationer eller förändrade arbetsförhållanden. Dessutom bidrar samtalen till att stärka individens medvetenhet om säkerhetsskyddsfrågor och deras eget ansvar för att skydda känslig information. Genom dessa samtal kan organisationer vidta åtgärder för att hantera eventuella identifierade säkerhetsrisker och upprätthålla en hög säkerhetsnivå.', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 51, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll nivå 1 - Meritmind', 'desc' => '● Verifiering av personnummer.</br>\r\n● De tre (3) sista deklarerade årsinkomsterna.</br>\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.</br>\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 1],
            ['id' => 52, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll nivå 2 - Meritmind', 'desc' => '● Verifiering av personnummer.</br>\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.</br>\r\n● De tre (3) sista deklarerade årsinkomsterna.</br>\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.</br>\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.</br>\r\n● CV­ kontroll</br>\r\n● Sociala medier</br>', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 5],
            ['id' => 53, 'service_cat_id' => 9, 'title' => 'Uppföljningssamtal - Konecranes AB', 'desc' => 'Årliga uppföljningssamtal enligt säkerhetsskyddslagen i Sverige är en del av arbetet med att säkerställa att anställda och andra personer med tillgång till säkerhetsklassad information eller verksamhet fortfarande är pålitliga ur säkerhetssynpunkt. Dessa samtal syftar till att uppdatera säkerhetsbedömningar och säkerställa att tidigare bedömningar om personens pålitlighet, lojalitet och sårbarhet är aktuella. De hjälper också till att identifiera eventuella förändringar i personens livssituation som kan påverka deras säkerhetsbedömning, såsom ekonomiska problem, nya relationer eller förändrade arbetsförhållanden. Dessutom bidrar samtalen till att stärka individens medvetenhet om säkerhetsskyddsfrågor och deras eget ansvar för att skydda känslig information. Genom dessa samtal kan organisationer vidta åtgärder för att hantera eventuella identifierade säkerhetsrisker och upprätthålla en hög säkerhetsnivå.', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 54, 'service_cat_id' => 1, 'title' => ' Grundutredning + Säkerhetsprövningsintervju - Fysisk - Konecranes AB', 'desc' => '<p>När kunden lägger sin beställning, anger de nödvändiga uppgifter såsom namn och kontaktinformation för kandidaten. Recway skickar därefter en bekräftelse på mottagandet av beställningen och informerar om nästa steg i processen. Kandidaten får ett informationsmejl från Recway med detaljer om intervjun, vad som förväntas och vilka dokument de ska ta med sig. Beställaren får en statusuppdatering som innehåller detaljer om intervjutiden och platsen.</p>', 'place' => 1, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 55, 'service_cat_id' => 1, 'title' => 'Volvo - Security clearance interview - Video ', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 56, 'service_cat_id' => 1, 'title' => 'Volvo - Security clearance interview - On-site ', 'desc' => '', 'place' => 1, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 57, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll nivå 1 - Sundsvalls Kommun', 'desc' => '● Verifiering av personnummer.</br>\r\n● De tre (3) sista deklarerade årsinkomsterna.</br>\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.</br>\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.\r\n', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 2],
            ['id' => 58, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll nivå 2 - Sundsvalls Kommun', 'desc' => '● Verifiering av personnummer.</br>\r\n● Nuvarande och tidigare folkbokföringsadress, samt eventuella in- och utvandringar.</br>\r\n● De tre (3) sista deklarerade årsinkomsterna.</br>\r\n● Betalningsförelägganden och skulder hos Kronofogdemyndigheten.</br>\r\n● Kontroll hos Sveriges samtliga tingsrätter, hovrätter och förvaltningsrätter.</br>\r\n● CV­ kontroll</br>\r\n● Sociala medier</br>', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 8],
            ['id' => 59, 'service_cat_id' => 3, 'title' => 'Personal investigation', 'desc' => 'Syftet är att bedöma personens pålitlighet, integritet och eventuella säkerhetsrisker.', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 62, 'service_cat_id' => 10, 'title' => 'Avslutande säkerhetssamtal', 'desc' => null, 'place' => 0, 'country' => 0, 'cost' => null, 'delivery_days' => null],
            ['id' => 63, 'service_cat_id' => 1, 'title' => 'Volvo - Compatibility Interview - Video ', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 64, 'service_cat_id' => 1, 'title' => 'Volvo - Compatibility Interview - On-site ', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => null],
            ['id' => 65, 'service_cat_id' => 9, 'title' => 'Volvo - Follow-up interview - Video ', 'desc' => 'Annual follow-up interviews in accordance with the Swedish Security Protection Act are part of the effort to ensure that employees and other individuals with access to classified information or operations remain trustworthy from a security perspective. These interviews aim to update security assessments and verify that previous evaluations regarding the individual\'s reliability, loyalty, and vulnerability are still valid. They also help identify any changes in the person\'s life situation that could impact their security assessment, such as financial issues, new relationships, or changes in work conditions. In addition, the interviews serve to raise the individual\'s awareness of security protection matters and reinforce their personal responsibility for safeguarding sensitive information. Through these interviews, organizations can take appropriate measures to manage any identified security risks and maintain a high level of security.\r\n', 'place' => 0, 'country' => 0, 'cost' => null, 'delivery_days' => null],
            ['id' => 66, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll - Spendrups ', 'desc' => '• Personalia \r\n• Ekonomi \r\n• Juridiska histroia \r\n• Körkortskontroll \r\n• Bolagesengagemang \r\n• Sociala Medier', 'place' => 0, 'country' => 0, 'cost' => 0, 'delivery_days' => 5],
            ['id' => 67, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll Nivå 1 - Solna Stad ', 'desc' => 'ID-verifiering\r\nPersonalia (adress, medborgarskap, arbetstillstånd)\r\nInkomstuppgifter (3 år)\r\nSkulder & ekonomisk status (Kronofogden)\r\nCV-kontroll (anställningar och utbildningar, 10 år)\r\nCV-analys\r\nRättslig kontroll (tingsrätt, förvaltningsrätt, hovrätter)\r\nUtökad personalia (andra på adressen, civilstånd, barn)\r\nSociala medier och medial närvaro\r\nBolagsengagemang (10 år)\r\nKonkurser', 'place' => 0, 'country' => 0, 'cost' => 2250, 'delivery_days' => 10],
            ['id' => 68, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll Nivå 2 - Solna stad', 'desc' => 'ID-verifiering\r\nPersonalia (adress, medborgarskap, arbetstillstånd)\r\nInkomstuppgifter (3 år)\r\nSkulder & ekonomisk status (Kronofogden)\r\nCV-kontroll (anställningar och utbildningar, 10 år)\r\nCV-analys\r\nRättslig kontroll (tingsrätt, förvaltningsrätt, hovrätter)\r\nUtökad personalia (andra på adressen, civilstånd, barn)\r\nSociala medier och medial närvaro\r\nBolagsengagemang (10 år)\r\nKonkurser\r\nKörkortskontroll\r\nFöreningsengemang\r\nBolagskontroll (omsättning, avgifter, ekonomiska signaler)\r\nSanktionslistor\r\nFordonsinnehav\r\nFastighetsinnehav', 'place' => 0, 'country' => 0, 'cost' => 3450, 'delivery_days' => 10],
            ['id' => 69, 'service_cat_id' => 3, 'title' => 'Säkerhetsprövning enligt Klass 2-  Solna stad ', 'desc' => 'ID-verifiering\r\nPersonalia (adress, medborgarskap, arbetstillstånd)\r\nInkomstuppgifter (3 år)\r\nSkulder & ekonomisk status (Kronofogden)\r\nCV-kontroll (anställningar och utbildningar, 10 år)\r\nCV-analys\r\nRättslig kontroll (tingsrätt, förvaltningsrätt, hovrätter)\r\nUtökad personalia (andra på adressen, civilstånd, barn)\r\nSociala medier och medial närvaro\r\nBolagsengagemang (10 år)\r\nKonkurser\r\nKörkortskontroll\r\nFöreningsengemang\r\nBolagskontroll (omsättning, avgifter, ekonomiska signaler)\r\nSanktionslistor\r\nFordonsinnehav\r\nFastighetsinnehav', 'place' => 0, 'country' => 0, 'cost' => 3450, 'delivery_days' => 10],
            ['id' => 70, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll Bas - Solna stad ', 'desc' => 'Personalia: namn, personnummer, adress och medborgarskap\r\nArbetstillstånd: kontroll vid behov\r\nEkonomisk bakgrund: aktuella och historiska ärenden hos Kronofogden\r\nRättslig kontroll:\r\n– Tingsrätt och förvaltningsrätt enligt folkbokföringshistorik och CV\r\n– Samtliga hovrätter i Sverige\r\nGranskning av sociala medier', 'place' => 0, 'country' => 0, 'cost' => 950, 'delivery_days' => 10],
            ['id' => 71, 'service_cat_id' => 3, 'title' => 'Säkerhetsprövning enligt Klass 3 -  Solna stad ', 'desc' => 'ID-verifiering\r\nPersonalia (adress, medborgarskap, arbetstillstånd)\r\nInkomstuppgifter (3 år)\r\nSkulder & ekonomisk status (Kronofogden)\r\nCV-kontroll (anställningar och utbildningar, 10 år)\r\nCV-analys\r\nRättslig kontroll (tingsrätt, förvaltningsrätt, hovrätter)\r\nUtökad personalia (andra på adressen, civilstånd, barn)\r\nSociala medier och medial närvaro\r\nBolagsengagemang (10 år)\r\nKonkurser\r\nKörkortskontroll\r\nFöreningsengemang\r\nBolagskontroll (omsättning, avgifter, ekonomiska signaler)\r\nSanktionslistor\r\nFordonsinnehav\r\nFastighetsinnehav', 'place' => 0, 'country' => 0, 'cost' => 3450, 'delivery_days' => 10],
            ['id' => 72, 'service_cat_id' => 1, 'title' => 'Säkerhetsprövningsintervju ', 'desc' => '', 'place' => 0, 'country' => 0, 'cost' => null, 'delivery_days' => null],
            ['id' => 73, 'service_cat_id' => 3, 'title' => 'Bakgrundskontroll nivå 1 - Skandia - Test', 'desc' => 'Personalia: namn, personnummer, adress och medborgarskap\r\nArbetstillstånd: kontroll vid behov\r\nEkonomisk bakgrund: aktuella och historiska ärenden hos Kronofogden\r\nRättslig kontroll:\r\n– Tingsrätt och förvaltningsrätt enligt folkbokföringshistorik och CV\r\n– Samtliga hovrätter i Sverige', 'place' => 0, 'country' => 0, 'cost' => null, 'delivery_days' => null],
        ];

        foreach ($interviews as $interview) {
            Interview::updateOrCreate(
                ['id' => $interview['id']],
                $interview
            );
        }
    }
}
