<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds statuses from the old `statuses` table.
 * IDs are preserved exactly from the old system.
 *
 * status_type references service_categories.id — only values 1, 3, 9, 10 exist.
 */
class StatusSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('statuses')->truncate();

        $now = now();
        $rows = array_map(fn ($r) => array_merge($r, ['created_at' => $now, 'updated_at' => $now]), $this->rows());

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('statuses')->insert($chunk);
        }

        // OLD system AUTO_INCREMENT was 78.
        DB::statement('ALTER TABLE statuses AUTO_INCREMENT = 78');
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }

    /** @return array<int, array<string, mixed>> */
    private function rows(): array
    {
        return [
            ['id' => 1,  'variable' => 'new_order',                          'status' => 'New Order',                              'status_detail' => 'New order created',                                       'status_icon' => 'bi bi-node-plus',          'color' => '#1A73E8', 'email_to' => '1,2',   'status_type' => 1,  'status_sv' => 'Ny beställning'],
            ['id' => 2,  'variable' => 'pending',                            'status' => 'Pending',                                'status_detail' => 'Pending',                                                 'status_icon' => 'bi bi-hourglass-split',    'color' => '#ffa200', 'email_to' => '1,2',   'status_type' => 1,  'status_sv' => 'Väntande'],
            ['id' => 3,  'variable' => 'booked',                             'status' => 'Booked',                                 'status_detail' => 'Interview has been booked',                               'status_icon' => 'bi bi-journal-check',      'color' => '#008B8B', 'email_to' => '1,2',   'status_type' => 1,  'status_sv' => 'Bokad'],
            ['id' => 4,  'variable' => 'approved',                           'status' => 'Approved',                               'status_detail' => 'Candidate has been approved',                             'status_icon' => 'bi bi-clipboard-check',    'color' => '#00FF00', 'email_to' => '1,2',   'status_type' => 1,  'status_sv' => 'Godkänd'],
            ['id' => 5,  'variable' => 'interview_interrupted',              'status' => 'Interview Interrupted',                  'status_detail' => 'Interview Interrupted',                                   'status_icon' => 'bi bi-x-square',           'color' => '#964B00', 'email_to' => '1,2',   'status_type' => 1,  'status_sv' => 'Intervju avbröts'],
            ['id' => 6,  'variable' => 'investigation_spo',                  'status' => 'Under investigation',                    'status_detail' => 'Candidate is under investigation',                        'status_icon' => 'bi bi-search',             'color' => '#ff6600', 'email_to' => '1,2',   'status_type' => 1,  'status_sv' => 'Under utredning'],
            ['id' => 7,  'variable' => 'denied',                             'status' => 'Denied',                                 'status_detail' => 'Candidate has been denied after meeting with SPO',        'status_icon' => 'bi bi-x-circle',           'color' => '#FF0000', 'email_to' => '1,2',   'status_type' => 1,  'status_sv' => 'Nekad'],
            ['id' => 9,  'variable' => 'canceledbycustomer',                 'status' => 'Canceled by customer',                   'status_detail' => 'Interview has been canceled by customer',                 'status_icon' => 'bi bi-trash',              'color' => '#7b94a8', 'email_to' => '1,2,3', 'status_type' => 1,  'status_sv' => 'Avbruten av kund'],
            ['id' => 10, 'variable' => 'Candidate_doesnot_answer',           'status' => "Candidate doesn't answer",              'status_detail' => "Candidate doesn't answer",                               'status_icon' => 'bi bi-envelope-slash',     'color' => '#416c96', 'email_to' => '1,2',   'status_type' => 1,  'status_sv' => 'Kandidaten svarar inte'],
            ['id' => 11, 'variable' => 'Did_not_showup',                     'status' => 'Did not show up',                        'status_detail' => 'Candidate did not show up',                               'status_icon' => 'bi bi-emoji-dizzy',        'color' => '#FF00FF', 'email_to' => '1,2',   'status_type' => 1,  'status_sv' => 'Dök inte upp'],
            ['id' => 13, 'variable' => 'new_order_background',               'status' => 'New Order',                              'status_detail' => 'New Order created for Background Check',                  'status_icon' => 'bi bi-node-plus',          'color' => '#1a73e8', 'email_to' => '',      'status_type' => 3,  'status_sv' => 'Ny beställning'],
            ['id' => 14, 'variable' => 'pending_background',                 'status' => 'Pending',                                'status_detail' => 'Pending',                                                 'status_icon' => 'bi bi-hourglass-split',    'color' => '#ffa200', 'email_to' => '',      'status_type' => 3,  'status_sv' => 'Väntande'],
            ['id' => 15, 'variable' => 'consent_sent',                       'status' => 'Consent Sent',                           'status_detail' => 'Consent has been sent to the candidate',                  'status_icon' => 'bi bi-check-all',          'color' => '#bbec09', 'email_to' => '',      'status_type' => 3,  'status_sv' => 'Samtycke skickat'],
            ['id' => 16, 'variable' => 'approval_received',                  'status' => 'Approval of consent Received',           'status_detail' => 'Received approval of the consent',                       'status_icon' => 'bi bi-box-arrow-in-down',  'color' => '#747d68', 'email_to' => '',      'status_type' => 3,  'status_sv' => 'Godkännande av samtycke mottaget'],
            ['id' => 17, 'variable' => 'research_started',                   'status' => 'Research Started',                       'status_detail' => 'Research Started',                                        'status_icon' => 'bi bi-bookmark-check',     'color' => '#ff9500', 'email_to' => '',      'status_type' => 3,  'status_sv' => 'Undersökning påbörjad'],
            ['id' => 18, 'variable' => 'results_received',                   'status' => 'Results Received',                       'status_detail' => 'Results of the background check have been received',     'status_icon' => 'bi bi-list-check',         'color' => '#7ebbfb', 'email_to' => '',      'status_type' => 3,  'status_sv' => 'Resultat mottagna'],
            ['id' => 19, 'variable' => 'rebooking',                          'status' => 'Rescheduling',                           'status_detail' => 'Interview has been Rescheduling',                         'status_icon' => 'bi bi-box-seam',           'color' => '#c3c2ff', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Omplanering'],
            ['id' => 21, 'variable' => 'deviation_bc',                       'status' => 'Deviation',                              'status_detail' => 'A deviation is found in the background check service',    'status_icon' => 'bi bi-bezier2',            'color' => '#ffd500', 'email_to' => '',      'status_type' => 3,  'status_sv' => 'Avvikelse'],
            ['id' => 22, 'variable' => 'approved_bc',                        'status' => 'Approved',                               'status_detail' => 'Candidate has been approved',                             'status_icon' => 'bi bi-check2-circle',      'color' => '#009419', 'email_to' => '',      'status_type' => 3,  'status_sv' => 'Godkänd'],
            ['id' => 23, 'variable' => 'still_not_booked',                   'status' => 'Still not booked',                       'status_detail' => 'The candidate has still not booked',                     'status_icon' => 'bi bi-exclamation',        'color' => '#e1962d', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Inte bokad än'],
            ['id' => 24, 'variable' => 'not_available',                      'status' => 'Not available',                          'status_detail' => 'Candidate not available',                                 'status_icon' => 'bi bi-bookmark-x',         'color' => '#8f1414', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Inte tillgänglig'],
            ['id' => 33, 'variable' => 'New_order_followuppinterview',       'status' => 'New Order',                              'status_detail' => 'Order added by customer',                                 'status_icon' => 'bi bi-arrow-bar-right',    'color' => '#000000', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Ny beställning'],
            ['id' => 34, 'variable' => 'pending_msg_follow',                 'status' => 'Pending',                                'status_detail' => 'Inväntar',                                                'status_icon' => 'bi bi-archive',            'color' => '#2e93ff', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Väntande'],
            ['id' => 35, 'variable' => 'booked_msg_follow',                  'status' => 'Booked',                                 'status_detail' => 'Kandidaten har bokat in sig',                            'status_icon' => 'bi bi-arrow-down-circle',  'color' => '#e0ecff', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Bokad'],
            ['id' => 36, 'variable' => 'notshow_msg_follow',                 'status' => 'Candidate didnt show up',                'status_detail' => 'Kandiodaten dök inte upp',                               'status_icon' => 'bi bi-arrow-90deg-right',  'color' => '#000000', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Dök inte upp'],
            ['id' => 37, 'variable' => 'Approved_followup',                  'status' => 'Approved',                               'status_detail' => 'Kandidaten har genomfört intervjun',                      'status_icon' => 'bi bi-emoji-smile',        'color' => '#00bd26', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Godkänd'],
            ['id' => 38, 'variable' => 'Candidate_canceled',                 'status' => 'Candidate canceled the booked appointment', 'status_detail' => 'Candidate canceled the booked appointment',          'status_icon' => 'bi bi-alarm',              'color' => '#ffa200', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Kandidaten avbokade det bokade mötet'],
            ['id' => 39, 'variable' => 'follow_up_under_investigation',      'status' => 'Under investigation',                    'status_detail' => 'Under investigation',                                     'status_icon' => 'bi bi-alarm',              'color' => '#eed34f', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Under utredning'],
            ['id' => 40, 'variable' => 'bkcanceledbycustomer',               'status' => 'Cancelled by customer',                  'status_detail' => 'Background check has been canceled by customer',         'status_icon' => 'bi bi-trash',              'color' => '#7b8fa8', 'email_to' => '',      'status_type' => 3,  'status_sv' => 'Avbruten av kund'],
            ['id' => 41, 'variable' => 'Interview_interup_flow',             'status' => 'Interview Interrupted',                  'status_detail' => 'Interview Interrupted',                                   'status_icon' => 'bi bi-alarm',              'color' => '#ad6500', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Intervju avbröts'],
            ['id' => 42, 'variable' => 'Denied_followup',                    'status' => 'Denied',                                 'status_detail' => 'Denied for followup',                                     'status_icon' => 'bi bi-basket-fill',        'color' => '#bc0104', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Nekad'],
            ['id' => 43, 'variable' => 'still_not_booked_followup',         'status' => 'Still not booked',                       'status_detail' => 'Candidate has still not booked',                          'status_icon' => 'bi bi-alarm',              'color' => '#e7eb24', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Inte bokad än'],
            ['id' => 44, 'variable' => 'Contactestablishedwith_thecandid',  'status' => 'Contact established with the candidate', 'status_detail' => 'Contact established with the candidate',                  'status_icon' => 'bi bi-alarm',              'color' => '#a69c11', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Kontakt etablerad med kandidaten'],
            ['id' => 45, 'variable' => 'Notavaila_Foloo',                   'status' => 'Not available',                          'status_detail' => 'Not available',                                           'status_icon' => 'bi bi-align-middle',       'color' => '#f0f269', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Inte tillgänglig'],
            ['id' => 46, 'variable' => 'Contactestablishedwith_thecanflow', 'status' => 'Contact established with the candidate', 'status_detail' => 'Contact established with the candidate',                  'status_icon' => 'bi bi-align-middle',       'color' => '#6687ff', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Kontakt etablerad med kandidaten'],
            ['id' => 47, 'variable' => 'Interviewcompletedwithout_deviation','status' => 'Interview completed without deviations', 'status_detail' => 'Interview completed without deviations',                  'status_icon' => 'bi bi-alarm',              'color' => '#81ff3d', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Intervju genomförd utan avvikelser'],
            ['id' => 49, 'variable' => 'new_order',                          'status' => 'New Order',                              'status_detail' => 'New order created',                                       'status_icon' => 'bi bi-node-plus',          'color' => '#1A73E8', 'email_to' => '1,2',   'status_type' => 10, 'status_sv' => 'Ny beställning'],
            ['id' => 50, 'variable' => 'pending',                            'status' => 'Pending',                                'status_detail' => 'Pending',                                                 'status_icon' => 'bi bi-hourglass-split',    'color' => '#ffa200', 'email_to' => '1,2',   'status_type' => 10, 'status_sv' => 'Väntande'],
            ['id' => 51, 'variable' => 'booked',                             'status' => 'Booked',                                 'status_detail' => 'Interview has been booked',                               'status_icon' => 'bi bi-journal-check',      'color' => '#008B8B', 'email_to' => '1,2',   'status_type' => 10, 'status_sv' => 'Bokad'],
            ['id' => 52, 'variable' => 'approved',                           'status' => 'Approved',                               'status_detail' => 'Candidate has been approved',                             'status_icon' => 'bi bi-clipboard-check',    'color' => '#00FF00', 'email_to' => '1,2',   'status_type' => 10, 'status_sv' => 'Godkänd'],
            ['id' => 53, 'variable' => 'interview_interrupted',              'status' => 'Interview Interrupted',                  'status_detail' => 'Interview Interrupted',                                   'status_icon' => 'bi bi-x-square',           'color' => '#964B00', 'email_to' => '1,2',   'status_type' => 10, 'status_sv' => 'Intervju avbröts'],
            ['id' => 54, 'variable' => 'investigation_spo',                  'status' => 'Under investigation',                    'status_detail' => 'Candidate is under investigation',                        'status_icon' => 'bi bi-search',             'color' => '#ff6600', 'email_to' => '1,2',   'status_type' => 10, 'status_sv' => 'Under utredning'],
            ['id' => 55, 'variable' => 'denied',                             'status' => 'Denied',                                 'status_detail' => 'Candidate has been denied after meeting with SPO',        'status_icon' => 'bi bi-x-circle',           'color' => '#FF0000', 'email_to' => '1,2',   'status_type' => 10, 'status_sv' => 'Nekad'],
            ['id' => 56, 'variable' => 'canceledbycustomer',                 'status' => 'Canceled by customer',                   'status_detail' => 'Interview has been canceled by customer',                 'status_icon' => 'bi bi-trash',              'color' => '#7b94a8', 'email_to' => '1,2,3', 'status_type' => 10, 'status_sv' => 'Avbruten av kund'],
            ['id' => 57, 'variable' => 'Candidate_doesnot_answer',           'status' => "Candidate doesn't answer",              'status_detail' => "Candidate doesn't answer",                               'status_icon' => 'bi bi-envelope-slash',     'color' => '#416c96', 'email_to' => '1,2',   'status_type' => 10, 'status_sv' => 'Kandidaten svarar inte'],
            ['id' => 58, 'variable' => 'Did_not_showup',                     'status' => 'Did not show up',                        'status_detail' => 'Candidate did not show up',                               'status_icon' => 'bi bi-emoji-dizzy',        'color' => '#FF00FF', 'email_to' => '1,2',   'status_type' => 10, 'status_sv' => 'Dök inte upp'],
            ['id' => 59, 'variable' => 'rebooking',                          'status' => 'Rescheduling',                           'status_detail' => 'Interview has been Rescheduling',                         'status_icon' => 'bi bi-box-seam',           'color' => '#c3c2ff', 'email_to' => '',      'status_type' => 10, 'status_sv' => 'Omplanering'],
            ['id' => 60, 'variable' => 'still_not_booked',                   'status' => 'Still not booked',                       'status_detail' => 'The candidate has still not booked',                     'status_icon' => 'bi bi-exclamation',        'color' => '#e1962d', 'email_to' => '',      'status_type' => 10, 'status_sv' => 'Inte bokad än'],
            ['id' => 61, 'variable' => 'not_available',                      'status' => 'Not available',                          'status_detail' => 'Candidate not available',                                 'status_icon' => 'bi bi-bookmark-x',         'color' => '#8f1414', 'email_to' => '',      'status_type' => 10, 'status_sv' => 'Inte tillgänglig'],
            ['id' => 62, 'variable' => 'Candidate_canceled',                 'status' => 'Candidate canceled the booked appointment', 'status_detail' => 'Candidate canceled the booked appointment',          'status_icon' => 'bi bi-alarm',              'color' => '#ffa200', 'email_to' => '',      'status_type' => 10, 'status_sv' => 'Kandidaten avbokade det bokade mötet'],
            ['id' => 63, 'variable' => 'Contactestablishedwith_thecandid',  'status' => 'Contact established with the candidate', 'status_detail' => 'Contact established with the candidate',                  'status_icon' => 'bi bi-alarm',              'color' => '#a69c11', 'email_to' => '',      'status_type' => 10, 'status_sv' => 'Kontakt etablerad med kandidaten'],
            ['id' => 65, 'variable' => 'Candidate_doesnot_answer',           'status' => "Candidate doesn't answer",              'status_detail' => "Candidate doesn't answer",                               'status_icon' => 'bi bi-envelope-slash',     'color' => '#416c96', 'email_to' => '1,2',   'status_type' => 9,  'status_sv' => 'Kandidaten svarar inte'],
            ['id' => 66, 'variable' => 'rebooking',                          'status' => 'Rescheduling',                           'status_detail' => 'Interview has been Rescheduling',                         'status_icon' => 'bi bi-box-seam',           'color' => '#c3c2ff', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Omplanering'],
            ['id' => 67, 'variable' => 'Interviewcompletedwithout_deviation','status' => 'Interview completed without deviations', 'status_detail' => 'Interview completed without deviations',                  'status_icon' => 'bi bi-alarm',              'color' => '#81ff3d', 'email_to' => '',      'status_type' => 10, 'status_sv' => 'Intervju genomförd utan avvikelser'],
            ['id' => 68, 'variable' => 'Referenser_klar',                    'status' => 'References completed',                   'status_detail' => 'References completed',                                    'status_icon' => 'bi bi-alarm',              'color' => '#e7e483', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Referenser klar'],
            ['id' => 69, 'variable' => 'consent_Reference_Received',        'status' => 'Consent & references received',          'status_detail' => 'Consent & references received',                           'status_icon' => 'bi bi-archive',            'color' => '#d5e78d', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Samtycket_referenserna_mottagna'],
            ['id' => 70, 'variable' => 'consent_referenser',                 'status' => 'Consent and references received',        'status_detail' => 'Consent_Recived',                                         'status_icon' => 'bi bi-align-bottom',       'color' => '#c3d57c', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Samtycketochreferensermottgna'],
            ['id' => 72, 'variable' => 'consent_Reference_Received2025',    'status' => 'Consent & references received',          'status_detail' => 'Consent & references received',                           'status_icon' => 'bi bi-arrow-90deg-up',     'color' => '#a1d454', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Samtycket_referenserna_mottagna'],
            ['id' => 73, 'variable' => 'Candidate_cancel_interview',        'status' => 'Candidate cancel interview',             'status_detail' => 'Candidate cancel interview',                              'status_icon' => 'bi bi-align-center',       'color' => '#98a300', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Kandidaten avbokade sin ti'],
            ['id' => 74, 'variable' => 'Customer_cancel_interiew_followup', 'status' => 'Customer cancel the order',             'status_detail' => 'Customer cancel the order',                               'status_icon' => 'bi bi-archive',            'color' => '#ff6905', 'email_to' => '',      'status_type' => 9,  'status_sv' => 'Kunden avbröt beställninge'],
            ['id' => 76, 'variable' => 'grundutreningreferensklar',          'status' => 'References & basic investigation completed', 'status_detail' => 'Grundtredning och referenstagning är klar',          'status_icon' => 'bi bi-alarm',              'color' => '#fd552b', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Referens och grundutredning kla'],
            ['id' => 77, 'variable' => 'Consent_Recived2',                   'status' => 'Consent received',                       'status_detail' => 'Consent_Recived2',                                        'status_icon' => 'bi bi-align-bottom',       'color' => '#e4e196', 'email_to' => '',      'status_type' => 1,  'status_sv' => 'Samtycket har inkommit'],
        ];
    }
}
